(cl:in-package computer_vision-msg)
(cl:export '(FRONTCAMFORWARDDISTANCE-VAL
          FRONTCAMFORWARDDISTANCE
          FRONTCAMHORIZONTALDISTANCE-VAL
          FRONTCAMHORIZONTALDISTANCE
          FRONTCAMVERTICALDISTANCE-VAL
          FRONTCAMVERTICALDISTANCE
))