// Generated by gencpp from file computer_vision/FrontCamera.msg
// DO NOT EDIT!


#ifndef COMPUTER_VISION_MESSAGE_FRONTCAMERA_H
#define COMPUTER_VISION_MESSAGE_FRONTCAMERA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace computer_vision
{
template <class ContainerAllocator>
struct FrontCamera_
{
  typedef FrontCamera_<ContainerAllocator> Type;

  FrontCamera_()
    : frontCamForwardDistance(0.0)
    , frontCamHorizontalDistance(0.0)
    , frontCamVerticalDistance(0.0)  {
    }
  FrontCamera_(const ContainerAllocator& _alloc)
    : frontCamForwardDistance(0.0)
    , frontCamHorizontalDistance(0.0)
    , frontCamVerticalDistance(0.0)  {
  (void)_alloc;
    }



   typedef float _frontCamForwardDistance_type;
  _frontCamForwardDistance_type frontCamForwardDistance;

   typedef float _frontCamHorizontalDistance_type;
  _frontCamHorizontalDistance_type frontCamHorizontalDistance;

   typedef float _frontCamVerticalDistance_type;
  _frontCamVerticalDistance_type frontCamVerticalDistance;




  typedef boost::shared_ptr< ::computer_vision::FrontCamera_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::computer_vision::FrontCamera_<ContainerAllocator> const> ConstPtr;

}; // struct FrontCamera_

typedef ::computer_vision::FrontCamera_<std::allocator<void> > FrontCamera;

typedef boost::shared_ptr< ::computer_vision::FrontCamera > FrontCameraPtr;
typedef boost::shared_ptr< ::computer_vision::FrontCamera const> FrontCameraConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::computer_vision::FrontCamera_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::computer_vision::FrontCamera_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace computer_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'computer_vision': ['/home/hero/Programming/catkin_lunar/src/computer_vision/msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::FrontCamera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::computer_vision::FrontCamera_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::computer_vision::FrontCamera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::computer_vision::FrontCamera_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::FrontCamera_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::computer_vision::FrontCamera_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::computer_vision::FrontCamera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65f5794fdf87a86db880b10f7ba78110";
  }

  static const char* value(const ::computer_vision::FrontCamera_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65f5794fdf87a86dULL;
  static const uint64_t static_value2 = 0xb880b10f7ba78110ULL;
};

template<class ContainerAllocator>
struct DataType< ::computer_vision::FrontCamera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "computer_vision/FrontCamera";
  }

  static const char* value(const ::computer_vision::FrontCamera_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::computer_vision::FrontCamera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 frontCamForwardDistance\n\
float32 frontCamHorizontalDistance\n\
float32 frontCamVerticalDistance\n\
";
  }

  static const char* value(const ::computer_vision::FrontCamera_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::computer_vision::FrontCamera_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frontCamForwardDistance);
      stream.next(m.frontCamHorizontalDistance);
      stream.next(m.frontCamVerticalDistance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FrontCamera_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::computer_vision::FrontCamera_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::computer_vision::FrontCamera_<ContainerAllocator>& v)
  {
    s << indent << "frontCamForwardDistance: ";
    Printer<float>::stream(s, indent + "  ", v.frontCamForwardDistance);
    s << indent << "frontCamHorizontalDistance: ";
    Printer<float>::stream(s, indent + "  ", v.frontCamHorizontalDistance);
    s << indent << "frontCamVerticalDistance: ";
    Printer<float>::stream(s, indent + "  ", v.frontCamVerticalDistance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMPUTER_VISION_MESSAGE_FRONTCAMERA_H
